### ISSUE TITLE
Change syntax for better compatibility with original obsidian

### ISSUE THREAD

**Issue by vosirandr** [MSzturc/obsidian-advanced-slides#137]
Change --- to ___ to create new slide

**Comment by ebullient** [comment]
This is a bit.. odd. --- works as a separator in obsidian (so you have a HR where slide breaks are when you aren't using the standard obsidian preview).

As a long-time user of reveal (and who still refers to the docs all the time because who has time to remember that?), changing the syntax would be strange...

**Comment by Crown0815** [comment]
I agree with @ebullient here. The `---` for slide separation is used in almost all markdown-to-presentation conversion tools. It would be quite odd to move away from it. 

Some examples:
- [reveal.js markdown support](https://revealjs.com/markdown/)
- [reveal.md](https://github.com/webpro/reveal-md)
- [mdx-deck](https://github.com/jxnblk/mdx-deck)

**Comment by MSzturc** [comment]
I agree both of you and since it's configurable through frontmatter i wont change the default values.

**Comment by vosirandr** [comment]
> I agree with @ebullient here. The `---` for slide separation is used in almost all markdown-to-presentation conversion tools. It would be quite odd to move away from it.
> 
> Some examples:
> 
> * [reveal.js markdown support](https://revealjs.com/markdown/)
> * [reveal.md](https://github.com/webpro/reveal-md)
> * [mdx-deck](https://github.com/jxnblk/mdx-deck)

Both options will have to work so if you do so
