### ISSUE TITLE
"New window" option is missing in general settings' dropdown menu

### ISSUE THREAD

**Issue by alltagsverstand** [MSzturc/obsidian-advanced-slides#155]
As the title suggests. According to the release notes of 1.18.1, there should be a corresponding option.

**Comment by MSzturc** [comment]
I had to remove this option. Currently when you open a View in a new Window, the submenu of this, wont be rendered. That's an issue, because toolbar of advanced slides wont show up. I've opened a ticked and hopefully it get's fixed in a future version of Obsidian, so that I could reactivate this Option in a future version. Sorry for the confusion. I've removed the part in the changelog.

**Comment by alltagsverstand** [comment]
I see - no problem! And thanks a lot for this wonderful plugin and all your work! :+1:
