### ISSUE TITLE
Feature request: turn off server

### ISSUE THREAD

**Issue by axelson** [MSzturc/obsidian-advanced-slides#169]
**Is your feature request related to a problem? Please describe.**
When I'm not actively using the server I'd like the server to be disabled to save battery/CPU

**Describe the solution you'd like**
When Obsidian starts there should be no slides server running on port 3000 (until the `Advanced Slides: Show Slide Preview` command is run). And also a command to manually shut down the server.

**Describe alternatives you've considered**
Uninstalling advanced slides when not actively working on a presentation

**Comment by peteretelej** [comment]
Additionally, (or maybe as a separate issue?), please consider changing the default port from :3000, as that is the default for react apps, and most nodejs apps. Since the slides server runs unmanaged in the background, it's a bit intrusive when using other tools that use the port and it's unlikely to be debugging the slides server

**Comment by peteretelej** [comment]
fyi or anyone having issues with the port number, you can change the port used from the plugin settings page. Which doesn't resolve the issue of the server running all the time but fixes the port conflict issues with other js apps
![image](https://user-images.githubusercontent.com/2271973/235629523-5d684a4b-d7ca-4b8d-be82-f6a0147bdbb6.png)

**Comment by axelson** [comment]
This should be fixed by https://github.com/MSzturc/obsidian-advanced-slides/pull/207#event-10382352630
