### ISSUE TITLE
text overflowing from slides

### ISSUE THREAD

**Issue by amorfati888** [MSzturc/obsidian-advanced-slides#187]
**Describe the bug**
Text overflowing from all my slides. Sorry if this issue was already adressed. I searched for keywords "overflow" and "grid" and didn't find anything.

**Samples to Reproduce**
- Using Windows 11.
- Opened a brand new obsidian vault.
- Installed only advanced slides. No other plugin.
- Using the tpl-footer.md template proposed [here](https://mszturc.github.io/obsidian-advanced-slides/templates/) as well as the example note.
- Attached the vault I'm using and screenshots.

Here is a screenshot of what it looks like
![Screenshot 2022-12-18 113443](https://user-images.githubusercontent.com/77325955/208293541-f318535b-4800-44fd-9807-bee49e6a8722.png)

Here is the sample vault I'm using to reproduce the bug:
[slidesTest.zip](https://github.com/MSzturc/obsidian-advanced-slides/files/10253596/slidesTest.zip)

**Expected behavior**
- Expected behavior is for the text to stay within the confines of the grid.

**Comment by MSzturc** [comment]
This is a normal behaviour. Since Advanced Slides is based on HTML it has to follow the rules and conventions of HTML. Scaling is very expensive and therefore there is no automatic way of doing this in HTML. 

I would suggest one of 2 way:

- Change the size of the slides - By default a slide is 960x700 pixel big. You can increase the size of slide which will reduce the size of the text by the frontmatter options `width` and `height`.

- You can annotate the element or the slide with a `<!-- .element: style="font-size: 16px" -->` to reduce font size it.
