### ISSUE TITLE
Presentations on Github Pages (or anywhere)

### ISSUE THREAD

**Issue by biscotty666** [MSzturc/obsidian-advanced-slides#226]
I'm enjoying working with your plug-in very much. I went through your documentation (and made a lot of notes in my vault), and have come up with an initial presentation.

But I don't find information on how to "give" the presentation other than making a video of me walking through it. Which is okay I guess. But...

Is there any way to specify a host for the presentation or is localhost the only option? If I could change that I could open a port on my router.

On your "Learn More" page in the documentation you have a number of examples of presentations live on Github Pages. How is this done? When I look at the presentation .md on github.io I just see the markdown.

Even if I could just get an html version I could run it on my own webserver.

Any guidance on this would be great. I feel like I have a lovely start of a presentation that I can't present.

Thanks in advance,
Brian

**Comment by stratosgear** [comment]
From the slides preview window you could click on the three dots menu and you can export your presentation as html pages.  Then you could host them anywhere you want, or even copy them on a usb stick and just open the index.html page, if you want to present your presentation without opening it from Obsidian.

**Comment by biscotty666** [comment]
Thanks.I couldn't find that anywhere.

⁣Get BlueMail for Android ​

**Comment by biscotty666** [comment]
I must be missing some plugin because I don't have that export option
available. I'll try to find the right one.

Thank you,
Brian

**Comment by biscotty666** [comment]
I have installed the following plugins:

Webpage HTML export
HTML Reader
Obsidian Enhanced Export
Pandoc Plugin

I can now export to html in many ways, but the html files only show
markdown. So it's a step forward, but the presentation just shows up as
a markdown file, not a presentation, when I open it with a webserver.

On export to html it offers to open the file after export, but after
briefly seeing the "Generating" window nothing opens up, but I can see
it on a locally running web server. Again, just not the presentation,
just the markdown.

I don't see the three dots menu you refer to. I have a hamburger menu
in the bottom left but that only opens a sidebar with the slides
listed.

Thanks in advance for any help you might be able to give me.


Brian



From the command palette I can now select Webpage Export HTML

**Comment by stratosgear** [comment]
This is what I meant:

![image](https://user-images.githubusercontent.com/193463/236003815-97acff1f-a7cb-40d9-833c-e84f8714c7ec.png)

(Ignore the red square at the bottom right. It's part of the slides template while I debug something)

And this is the list of plugins I have installed:

![image](https://user-images.githubusercontent.com/193463/236004384-beec78cc-c92a-463b-a647-7758d948a625.png)

I have set, in the Commuity plugins > Advanced Slides > Export Directory  the directory name to be `export_presentations` and in that folder I get to see a folder with the following contents (unzipped! I just zipped them to upload them here)

[vertical slides failure example.zip](https://github.com/MSzturc/obsidian-advanced-slides/files/11388846/vertical.slides.failure.example.zip)

I do not know what other info you might require in order to recreate the functionality that I thought was a default one... :(

**Comment by biscotty666** [comment]
Thank you for your response. For some reason I do not have that menu available to me.

![image](https://github.com/MSzturc/obsidian-advanced-slides/assets/107413839/79a5c844-8903-4184-bfbb-303eb5be911d)

**Comment by biscotty666** [comment]
OK, now I know what everyone is talking about. I found the setting below, turned it on, and I have access to those items in the tab bar. Happiness! Plus there's other cool things there too even in the regular tabs, like the view changing icon. I was wondering why every video I saw had that icon and I didn't lol. That didn't bug me really but this is functionality which relies on an innocuous setting in the Appearances section.

Anyway, works as advertised now!! Love the product and thanks for the help.
