### ISSUE TITLE
Show nothing when click 'show slide preview'

### ISSUE THREAD

**Issue by woshichuanqilz** [MSzturc/obsidian-advanced-slides#235]
**Describe the bug**
Show nothing when click 'show slide preview'
![image](https://github.com/MSzturc/obsidian-advanced-slides/assets/11295355/26158031-ee89-4f3d-990b-a09022e4a1f5)

**Samples to Reproduce**
Steps & Examples to reproduce the behavior:
1. install this plugin 
2. create a new note with content 
```
# ori
--- 
# 2
```
show nothing 

**Expected behavior**
show the slides

**Comment by zickzackv** [comment]
Same Problem for me. From the the developer console:

> caught (in promise) Error: ENOENT: no such file or directory, open '/Users/fabian.otto/Source/READMEs/.obsidian/plugins/obsidian-advanced-slides/template/reveal.html'
a

**Comment by RiverOmega** [comment]
Same for me!

**Comment by zickzackv** [comment]
```
server started at http://localhost:3001
plugin:obsidian-jira-issue:10160 Error while retrieving custom fields list of account: Default Error: Error: net::ERR_EMPTY_RESPONSE
    at sendRequest (plugin:obsidian-jira-issue:10016:11)
    at async Object.updateCustomFieldsCache (plugin:obsidian-jira-issue:10140:26)
updateCustomFieldsCache @ plugin:obsidian-jira-issue:10160
plugin:obsidian-advanced-slides:318 Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Users/zickzackv/Source/READMEs/.obsidian/plugins/obsidian-advanced-slides/template/reveal.html'
plugin:obsidian-advanced-slides:336 Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12)
```

My firefox connecting to http://localhost:3001 waits for ever. At least its waiting now! Sadly still not a fix for me.

**Comment by bducasse33** [comment]
I had this problem after installing multiple other plugins. I thought maybe one of them was conflicting somehow with Advanced Slides. I tried disabling them one by one, then uninstalling them. Still same problem. Finally I copied all of my notes to a new directory and started a fresh vault from there. I installed Advanced Slides and everything works fine. Now I'm reinstalling other plugins one at a time to see if I can identify one that was causing a problem. Maybe worth a try.

**Comment by zickzackv** [comment]
Found the root cause of my problem!

I'm running Obsidian on my work laptop which has restricted network access. All TLS certificates are intercepted and replaced by our own certificates.

The plugins are downloaded with obsidians downloader which uses the systems cert store including the replaced root cert. I'm guessing that the plugin itself downloads the javascript files with its own node code which uses a different cert store. So the plugin could not download its presenter javascript files.

Temporarly disabling the MITM Proxy and installing the plugin again allowed it to download its files.

My case is now closed. Thanks!

**Comment by woshichuanqilz** [comment]
> In the settings I changed the port from 3000 to something else: ![image](https://user-images.githubusercontent.com/15626786/246770933-8483010b-5809-4391-af41-8f2f00ad6088.png)
> 
> ... and now it works. Try that and see if it helps.

It is right for me the port issue.

**Comment by ryanklee** [comment]
For anyone experiencing this issue due to Zscaler or the like, one hacky, security-risky workaround is to add the following line to the head of main.js in the plugin directory:

`process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';
`

This won't survive any updates, to the file, of course, but works in the interim.
