### ISSUE TITLE
[suggestion] Expose configuration options to plugin's setting panel

### ISSUE THREAD

**Issue by cztuc** [MSzturc/obsidian-advanced-slides#25]
Hi there,

Thanks __very__ much for continuously polishing this very useful plugin.

I have a tiny suggestion: is it possible to let the user set some (default) options in the plugin's setting panel?

Currently, we need to configure this plugin in each MD file's front matter. Sometimes, it feels redundant when you have many different presentations, while you want to set exactly the same configuration, i.e. theme, transition... What do you think? Maybe this feature is already on your plan?

Thanks!

**Comment by wenlzhang** [comment]
This can be very useful.

**Comment by MSzturc** [comment]
I'm torn as to what to think about this feature request. On the one hand, I understand that it would be a good convenience function, on the other hand, it feels wrong that presentations that are finished and that functioned as if they should once no longer work, because a setting such as verticalSeparator in the settings has been changed. 

That feels wrong to me.

**Comment by MSzturc** [comment]
added global settings for theme, highlight theme, transition and transition speed with 1.5.0
