### ISSUE TITLE
Feature: support icon shortcode

### ISSUE THREAD

**Issue by aidenlx** [MSzturc/obsidian-advanced-slides#35]
Hi! First of all, glad to see icons implemented in latest version! I'm the dev of [Icon shortcodes plugin](https://github.com/aidenlx/obsidian-icon-shortcodes), which provides Font Awesome, Remixicon icons out of the box, and allow user to import any custom icon they have. Adding support for icon shortcodes would help user a lot in case they need to use their custom icons. 

You can check here for details about its api: <https://github.com/aidenlx/obsidian-icon-shortcodes#for-developer>, for the use case of advanced slides, you can utilize [the exposed post processor](https://github.com/aidenlx/obsidian-icon-shortcodes/blob/0db5a0a925fb2067d3e1dc7ac063d0edb87f91e3/src/typings/api.ts#L94), which will replace every `:shortcode:` with image. (source code is [here](https://github.com/aidenlx/obsidian-icon-shortcodes/blob/master/src/modules/post-ps.ts))

feel free to ask if you have any question :)

**Comment by MSzturc** [comment]
Cool plugin, I didn't know it yet. 

In terms of integration, it will probably not be that easy.
I developed advanced slides with the idea that it also has to run from the command line, so that it can be used for example from a github action to transform slides in static pages. Therefore I have separated the transformation core from the obsidian plugin. The core knows the Markdown only as string, so i wont be able to use your markdownProcessor. 


Would you mind extracting the core logic from the markdown processor and providing it to me with the following interface?

```
	process(markdown: string): string;
```

Otherwise I could simply reprogram the Markdown processor, it's not that complex, but that would duplicate code, which I dont prefer

**Comment by aidenlx** [comment]
I see, that should be doable, I’ll inform you when it’s avaliable. In terms of transforming into static page, the current api provide custom icons (stored as file in `.obsidian/icons`) with the resource url usable only in obsidian. Do you need the absolute paths to those icon files so that it can be used/copied?

**Comment by aidenlx** [comment]
[icon shortcode v0.6.2](https://github.com/aidenlx/obsidian-icon-shortcodes/releases/tag/0.6.2) includes two api updates: 
1. `postProcess()` can now accept string + replacer function
2. new `getIconData(id)` function that provides essential data for icons: 
    1. `type="emoji"`: `char` that includes emoji character
    2. `type="built-in"`: `data` with original svg file content, and `dataUri` with converted svg data uri
    3. `type="file"`: `fsPath` with icon file path in file system, and `resourcePath` with icon resource path usable in obsidian

**Comment by aidenlx** [comment]
btw, if you need to use this in command line env, I would suggest preprocess markdown and convert all shortcodes to emoji char/`<img src="PATH_TO_FILE/DATA_URI">`, otherwise you need to implement the logic of finding corresponding imported icon from `.obsidian/icons` in your cli program.

**Comment by MSzturc** [comment]
Cool looks good, will incorporate it in the coming days. As far as cmd line functionality is concerned, I still have to decide in which direction I should use with the plugin.

It's just annoying that obsidian is not open source because I would prefer to build a headless version of it that I can use for rendering the slides (including all plugins). I would like to have the possibility of integrating dataviews or trackers as tables and charts into advanced slides, but then I lose the possibility of running advanced slides from the command line.

**Comment by MSzturc** [comment]
Yeah you're right. Font Awesome enhances the svg data in the [css/js](https://github.com/FortAwesome/Font-Awesome/blob/7d3d774145ac38663f6d1effc6def0334b68ab7e/js/fontawesome.js#L1787) part.
