### ISSUE TITLE
Failed to load plugin 1.5.0

### ISSUE THREAD

**Issue by jcmoral90** [MSzturc/obsidian-advanced-slides#36]
Hi, i have problems to enable v 1.5.0 in Obsidian

**Comment by MSzturc** [comment]
please retry with 1.5.1

**Comment by jcmoral90** [comment]
now it won't let me install 
![imagen](https://user-images.githubusercontent.com/64127850/147999651-aaad2d06-135c-4a8c-ba0f-a518bb2cf8cb.png)

**Comment by MSzturc** [comment]
Strange, please share a screenshot of your developer console (view->toggle developer tools )

**Comment by jcmoral90** [comment]
![imagen](https://user-images.githubusercontent.com/64127850/148000291-6388cc98-5475-45b1-bd22-715b157a88e5.png)

**Comment by MSzturc** [comment]
Well seams that there is a problem with your internet connection or maybe with github itself the manifest.json is in the repository and im able to download it when i activate advanced slides. When activating advanced slides it checks if there is an updated distribution of reveal and downloads it. Please restart Obsidian, and check if the problem still appears. If its still happens, please reinstall advanced slides ( it could be that advanced slides is corrupt since the update had failed)

**Comment by jcmoral90** [comment]
I have no problems with my connection, I still rebooted. The problem persists, then I uninstall and reinstall BRAT, then I try again with the Community PLugin. The plugin is installed but not enabled. 

PS: I don't know how to update reveal, I consider myself a consumer of obsidian plugins only.

**Comment by MSzturc** [comment]
please retry with version 1.5.4

**Comment by jcmoral90** [comment]
Yesss!, now with 1.5.4 I can just log in. Thank u very much @MSzturc
