### ISSUE TITLE
Split Components doesn't work

### ISSUE THREAD

**Issue by EhuddR** [MSzturc/obsidian-advanced-slides#39]
Hi! 

First of all, thank you for this amazing tool. I was waiting for something like this plugin for a long time. I would like to inform that the Split component does not work with text elements. I was able to make it work with images tho.

**Images**
![image](https://user-images.githubusercontent.com/78237982/148313801-e26b53b9-d205-455d-b98e-400128f7bfec.png)

**Text**
![image](https://user-images.githubusercontent.com/78237982/148313845-24698133-9d0f-4f06-a647-df21b863a3d2.png)

**Comment by MSzturc** [comment]
This is n problem of the obsidian markdown transformer. Please have a look at the line under `<split even gap="3">`. There should be an invisible character, i would guess a tab which causes obsidian to wrap the content in a div element. This is something i couldnt fix properly since its an special behavior that is obsidian specific, not markdown
