### ISSUE TITLE
Error when opening external links in Chrome

### ISSUE THREAD

**Issue by wenlzhang** [MSzturc/obsidian-advanced-slides#9]
External links open normally when previewing the slides in Obsidian. However, there are the following errors when previewing the slides and opening the links in Chrome:
![Screenshot 2021-12-16 at 13 07 42](https://user-images.githubusercontent.com/44930227/146369748-dfa7bf41-363f-4a33-8aea-eed6a2aa815e.png)

**Comment by MSzturc** [comment]
Can you provide me a markdown sample to reproduce this problem?

**Comment by wenlzhang** [comment]
Sure. Here is a Markdown file that results in this issue:
```
---
theme: sky
highlightTheme: monokai
css: []

verticalSeparator: <!-- -->
fragments: true
previewLinks: true

notesSeparator: 'note:'
showNotes: false
defaultTime: null
navigationMode: 'default'

progress: true
slideNumber: true
overview: true
center: true
rtl: false

controls: true
controlsTutorial: true
controlsLayout: 'bottom-right'
controlsBackArrows: 'faded'

transition: 'convex'
transitionSpeed: 'default'
backgroundTransition: 'fade'

keyboard: true
touch: true
mouseWheel: false
pause: true

loop: false
shuffle: false
autoSlide: 0

help: true
---

## External link

- [Google](https://www.google.com/)

```

**Comment by MSzturc** [comment]
Ohh wow... 

that is something i didn't expected. You're a bigger reveal nerd than i am ;-)
I've debugged that problem a bit and found out that the previewLinks property causes this issue. Currently i have no clue why this happens

```
---
previewLinks: true
---

## External link

- [Google](https://www.google.com/)
```

**Comment by wenlzhang** [comment]
> that is something i didn't expected. You're a bigger reveal nerd than i am ;-)

hahaha :-)

I can confirm that the Obsidian link works in Chrome. In fact, I realized this issue because I cannot open a GitLab repository link and an internal link from a website of my employer either.

**Comment by MSzturc** [comment]
You can find more informations about it [here](https://stackoverflow.com/questions/27358966/how-to-set-x-frame-options-on-iframe)

To fix this issue reveal.js would have to create a workaround for this "feature" and since it's a security features that is sensible i cant imagine they will do it.

It's used to prevent embedding a side in another side which make scam attacks impossible

Imagine someone embeds google.com in his side and you would use this to login into your google account. The attack would be able to sniff your credentials.
