### ISSUE TITLE
Why isn't iPad supported?

### ISSUE THREAD

**Issue by sharrissf** [MSzturc/obsidian-advanced-slides#92]
Subject is self explanatory :-)

**Comment by MSzturc** [comment]
It's not possible to support an iPad since app policy of Apple is to restricted since the runtime of Adanced Slides is using an Webserver for the live preview and the rendering of the slides (which apple doesn't allow). But you could use your ipad in exported presentation or as second monitor when it's connected to an macbook for example. I use both workflow myself.
